
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: NowSecure Platform Integration
      uses: blawrencens/nowsecure-actions-integration@1.0.3
      with:
        # Please provide the path for the app to be uploaded
        app-path: "/home/runner/work/CIIntegration/CIIntegration/anydo39.apk"
        # Please provide the API Key for NowSecure Platform
        api-key: ${{ secrets.PLATFORM_API_KEY }}
        # Please provide the Group Id of the application being integrated
        group-id: "a27a22b7-d9a0-4b1e-81b8-0f847029e0f5"
